services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ~/hackdays/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=link_our_teachers